# Generated by Django 3.0.3 on 2020-07-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commonops', '0003_auto_20200716_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(upload_to='uploads/videos/')),
                ('collections', models.ManyToManyField(to='dashboard.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonops.User', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='uploads/pictures/')),
                ('collections', models.ManyToManyField(to='dashboard.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonops.User', verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('track', models.FileField(upload_to='uploads/music/')),
                ('collections', models.ManyToManyField(to='dashboard.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonops.User')),
            ],
        ),
    ]
