# Generated by Django 3.1.4 on 2021-02-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
