# Generated by Django 3.0.3 on 2020-07-16 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 54, 22, 979550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 54, 22, 983547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 54, 22, 980549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 16, 18, 54, 22, 981548, tzinfo=utc)),
        ),
    ]
