# Generated by Django 3.1.4 on 2021-02-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210219_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='art',
            field=models.ImageField(blank=True, default='default/screen-0.jpg', null=True, upload_to='arts/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/Video.jpg', null=True, upload_to='thumbnails/'),
        ),
    ]
