# Generated by Django 3.0.3 on 2020-07-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200716_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
