# Generated by Django 3.0.3 on 2020-07-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0004_auto_20200716_2157'),
        ('dashboard', '0003_auto_20200716_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to='media/music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonops.User', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='media/pictures/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
