# Generated by Django 3.0.3 on 2020-07-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200719_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
