# Generated by Django 3.0.3 on 2020-11-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0006_auto_20201123_0231'),
        ('dashboard', '0007_auto_20201123_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commonops.User')),
            ],
        ),
    ]
