# Generated by Django 3.0.3 on 2020-12-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20201205_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='video',
            name='collections',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
