# Generated by Django 3.0.3 on 2020-12-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201205_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='tag',
            new_name='tags',
        ),
    ]
