# Generated by Django 3.1.4 on 2021-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20201205_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='art',
            field=models.ImageField(default='default/screen-0.jpg', upload_to='arts/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default/Video.jpg', upload_to='thumbnails/'),
        ),
    ]
