# Generated by Django 3.1.4 on 2021-02-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_fan',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Preffers dark theme'),
        ),
    ]
