# Generated by Django 3.0.3 on 2020-07-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0002_auto_20200716_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
