# Generated by Django 3.0.3 on 2020-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0004_auto_20200716_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2020-08-07', verbose_name='Birth Date'),
            preserve_default=False,
        ),
    ]
