# Generated by Django 3.0.3 on 2020-11-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonops', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
